version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:5000
    # environment:
    #   - UPLOAD_PATH=/images
    #   - UPLOADED_PATH=/app/api/media/images
    volumes:
      - ./images:/app/app/api/media/images
      - ./images:/app/images
      - ./app/api/media:/app/app/api/media
