import dumpfile from './dumpinformation.json';
const prisma = new PrismaClient();
//use this to remove id, if you use an autogenerated ID
const artistData = JSON.parse(dumpfile).map(({ id, ...rest }) => rest);

// //insert data to current db
await prisma.child_developers.createMany({ data: artistData });